// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// For more information, please visit:
// https://firebase.google.com/docs/build

import {initializeApp, getApp, getApps} from 'firebase/app';

const firebaseConfig = {
  "apiKey": "YOUR_API_KEY",
  "authDomain": "YOUR_AUTH_DOMAIN",
  "projectId": "YOUR_PROJECT_ID",
  "storageBucket": "YOUR_STORAGE_BUCKET",
  "messagingSenderId": "YOUR_MESSAGING_SENDER_ID",
  "appId": "YOUR_APP_ID"
};

function initializeAppIfNecessary() {
  try {
    return getApp();
  } catch {
    return initializeApp(firebaseConfig);
  }
}

const app = initializeAppIfNecessary();
